// ── Peer Review — Synthesizes multiple LLM responses ──

const { providerRegistry } = require('../providers/provider-registry');
const { ApiPtyEmitter } = require('../providers/api-pty-emitter');

class PeerReview {
  /**
   * Synthesize multiple LLM responses into a comparative analysis.
   *
   * @param {Array<{providerId, model, response}>} responses - Collected responses
   * @param {string} originalPrompt - The user's original message
   * @param {object} opts
   * @param {string} opts.reviewerId - Provider to use as reviewer (default: 'claude')
   * @param {string} opts.reviewerModel - Model for the reviewer
   * @param {string} opts.sessionId - Session ID for output
   * @param {Electron.WebContents} opts.webContents - For streaming output
   * @returns {Promise<string>} Synthesis text
   */
  static async synthesize(responses, originalPrompt, opts = {}) {
    const reviewerId = opts.reviewerId || 'claude';
    const reviewer = providerRegistry.getProvider(reviewerId);

    if (!reviewer) {
      throw new Error(`Reviewer provider not available: ${reviewerId}`);
    }

    // Build the synthesis prompt
    const synthesisPrompt = PeerReview._buildPrompt(responses, originalPrompt);

    // For Claude (PTY), we can't easily use the API path —
    // fall back to a non-Claude reviewer or use the first available API provider
    let actualReviewer = reviewer;
    let actualReviewerId = reviewerId;

    if (reviewerId === 'claude') {
      // Try to use an API-based provider for synthesis since Claude uses PTY
      const apiProviders = ['openai', 'gemini', 'ollama'];
      for (const pid of apiProviders) {
        const p = providerRegistry.getProvider(pid);
        if (p && p.isConfigured()) {
          actualReviewer = p;
          actualReviewerId = pid;
          break;
        }
      }

      // If only Claude is available, return a formatted comparison without AI synthesis
      if (actualReviewerId === 'claude') {
        return PeerReview._staticComparison(responses, originalPrompt);
      }
    }

    const synthesisSessionId = `${opts.sessionId || 'synthesis'}__review`;
    const model = opts.reviewerModel || (await actualReviewer.models())[0]?.id;

    await actualReviewer.createSession(synthesisSessionId, {
      model,
      systemPrompt: 'You are an expert analyst synthesizing responses from multiple AI models. Be concise, insightful, and highlight key differences and agreements.',
    });

    // Stream the synthesis
    if (opts.webContents) {
      const emitter = new ApiPtyEmitter(opts.webContents, synthesisSessionId, actualReviewerId);
      const generator = actualReviewer.sendMessage(synthesisSessionId, synthesisPrompt);
      await emitter.streamResponse(generator, `Synthesis (${actualReviewer.displayName})`);
    }

    // Collect the full response
    let fullSynthesis = '';
    const generator = actualReviewer.sendMessage(synthesisSessionId, synthesisPrompt);
    for await (const chunk of generator) {
      if (chunk.type === 'text') fullSynthesis += chunk.content;
    }

    actualReviewer.destroy(synthesisSessionId);
    return fullSynthesis;
  }

  /**
   * Build the synthesis meta-prompt.
   */
  static _buildPrompt(responses, originalPrompt) {
    let prompt = `## Multi-LLM Peer Review\n\n`;
    prompt += `**Original Prompt:** ${originalPrompt}\n\n`;
    prompt += `The following responses were generated by different AI models for the same prompt. `;
    prompt += `Analyze them and provide:\n`;
    prompt += `1. **Consensus** — What all models agree on\n`;
    prompt += `2. **Divergences** — Where models disagree and why\n`;
    prompt += `3. **Strengths** — Best insights from each model\n`;
    prompt += `4. **Gaps** — What all models missed\n`;
    prompt += `5. **Recommended Answer** — Your synthesized best response\n\n`;
    prompt += `---\n\n`;

    for (const r of responses) {
      if (r.status !== 'complete' && r.status !== 'fulfilled') continue;
      const response = r.response || '';
      const truncated = response.length > 3000 ? response.slice(0, 3000) + '\n[truncated]' : response;
      prompt += `### ${r.providerId.toUpperCase()} (${r.model})\n\n${truncated}\n\n---\n\n`;
    }

    return prompt;
  }

  /**
   * Fallback: static comparison when no API provider is available for synthesis.
   */
  static _staticComparison(responses, originalPrompt) {
    let output = `\n═══ MULTI-LLM COMPARISON ═══\n\n`;
    output += `Prompt: ${originalPrompt.slice(0, 200)}\n\n`;

    for (const r of responses) {
      const status = r.status === 'complete' ? '✓' : '✗';
      const duration = r.duration ? `(${(r.duration / 1000).toFixed(1)}s)` : '';
      output += `── ${r.providerId.toUpperCase()} / ${r.model} ${status} ${duration} ──\n`;
      output += `${(r.response || 'No response').slice(0, 500)}\n\n`;
    }

    output += `═══ END COMPARISON ═══\n`;
    return output;
  }
}

module.exports = { PeerReview };
